services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v25.1.5
    container_name: redpanda
    command:
      - redpanda start
      -  --smp 1
      -  --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      -  --advertise-kafka-addr internal://redpanda:9092,external://localhost:19092
      - --advertise-pandaproxy-addr internal://redpanda:8082,external://localhost18082
      - --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:18081
      - --rpc-addr redpanda:33145
      - --advertise-rpc-addr redpanda:33145
    ports:
      - 8081:8081
      - 18081:18081
      - 19092:19092
      - 19644:9644
